path: c\company
type: type
ws: ws name
skip: False
# skip: True
year_quarter:
  - [2020, 2]
  - [2020, 3]
  - [2020, 4]
  - [2021, 1]
  - [2021, 2]
  - [2021, 3]
dropbox_path: path\to\dropbox
# payroll_dir: "Payroll & Worksheet"
payroll_dir: "Payroll And Worksheet"
