path: c\company\ERTC  # Sometimes there is no ERTC dir
type: type   # Company type (LA|TSP)
ws: ws name  # The worksheet name sans extension
skip: False  # Skip creating the 8821
payroll_dir: "Payroll And Worksheet"  # Some people use an &
dropbox_path: C:\Users\<user>\FMS Dropbox
year_quarter:  # Comment out any line and you will skip creating that 941
  - [2020, 2]
  - [2020, 3]
  - [2020, 4]
  - [2021, 1]
  - [2021, 2]
  - [2021, 3]
excel_sheet_names:
  input: "Data Input"
  2020Q2: "2020 Q2 941 Calc"
  2020Q3: "2020 Q3 941 Calc"
  2020Q4: "2020 Q4 941 Calc"
  2021Q1: "2021 Q1 941 Calc"
  2021Q2: "2021 Q2 941 Calc"
  2021Q3: "2021 Q3 941 Calc"
