types:
  - LA
  - TSP
companies:
  - 
skip: False
# skip: True
payroll_dirs:
  - "payroll & worksheet"
  - "payroll and worksheet"
year_quarter: # comment out reports to skip
  - [2020, 2]
  - [2020, 3]
  - [2020, 4]
  - [2021, 1]
  - [2021, 2]
  - [2021, 3]
dropbox_path: 
excel_sheet_names:
  input: "Data Input"
  2020Q2: "2020 Q2 941 Calc"
  2020Q3: "2020 Q3 941 Calc"
  2020Q4: "2020 Q4 941 Calc"
  2021Q1: "2021 Q1 941 Calc"
  2021Q2: "2021 Q2 941 Calc"
  2021Q3: "2021 Q3 941 Calc"
round_delta: 0.001
row_2020: 46
row_2021: 47
f941x_file_name: "f941x 8-9-22.pdf"
f8821_file_name: "f8821 8-9-22.pdf"
base_ws_name: ERTC Worksheet for 941x prep
